<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Text Decorator</title>
    </head>
    <body>
        <h1>Text Decorator</h1>

        <div>
            <?= $text?>
        </div>

        <form action="" method="POST">
            <?php foreach($decorators as $d) : ?>
                <input name="choices[]" type="checkbox" value="<?=$d ?>">
                <?= $d ?>
            <?php endforeach; ?>
            ​
            <div>
                <button type="submit"> Envoyer </button>
            </div>
        </form>  ​
    </body>
</html>