<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <title>Document</title>
</head>
<body>
<article>
    <?php foreach ($news as $article) : ?>

        <?php if ($article->getImageUrl()) : ?>
            <img src="<?= $article->getImageUrl(); ?>" alt="<?= $article->getTitle(); ?>">
        <?php endif; ?>

        <div>
            <h2>
                <a href="<?= $article->getUrl(); ?>">
                    <?= $article->getTitle(); ?>
                </a>
            </h2>
            <p><?=  mb_substr($article->getDescription(), 0, 160) . '...' ?></p>
        </div>

    <?php endforeach; ?>
</article>
</body>
</html>



